# Generated by Django 4.0.6 on 2022-09-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangdori', '0002_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(db_column='phone', max_length=30, verbose_name='phone'),
        ),
    ]
