# Generated by Django 4.1.2 on 2022-11-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
